version: "3.8"

services:
  next-app:
    build:
      context: ./next-app
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/myapp
      - NEXT_PUBLIC_API_URL=http://server:5000
      - NODE_ENV=development
    volumes:
      - ./next-app:/app
      - /app/node_modules
    depends_on:
      - server
      - mongodb
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/myapp
    volumes:
      - ./server:/app
      - ./server/received_pdfs:/app/received_pdfs
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=myapp
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
